sudo: required
dist: trusty

services:
  - docker

language: java
jdk:
  - oraclejdk8

install:
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - "export PATH=`pwd`/bin:$PATH"
  - echo $HOME
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - export DISPLAY=:99.0 && mvn clean test
